import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/contexts/AuthContext";  // ✅ ADD THIS

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-background antialiased ${poppins.className}`}
      >
        <NextTopLoader />

        {/* ✅ WRAP YOUR ENTIRE APP HERE */}
        <AuthProvider>
          {children}
        </AuthProvider>

        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
